### ISSUE TITLE
Shiny Sprites

### ISSUE THREAD

**Issue by spacegothprincess** [spacedogprincess/frlgrse_dynamic_pokemon_tracker#7]
Loading a Shiny Pokemon into the party does not render the pokemon, and halts the code from updating without a reset.

Refer to logs for 2022-03-25

**Comment by jaas666** [comment]
I submitted PR #8 

Hopefully that helps

**Comment by spacegothprincess** [comment]
Fixed it like a charm and perfectly worked in my active build for streaming! Thank you for your contribution.
